### ISSUE TITLE
no license  is pecified

### ISSUE THREAD

**Issue by avg-I** [kuba--/xattr#2]
No license is specified for the software, but it would be nice if you, as the author, explicitly stated license conditiond.
FWIW, https://github.com/davecheney/xattr has a license file that requires that a copyright notice is reproduced.  Not sure, maybe you forked that code before the license was added.

**Comment by kuba--** [comment]
I do not remember. The truth is that most of this code was copied/inspired from Dave's repo.
So I'm not sure what's the right thing for current case. I can copy Dave's LICENSE (and add my name to it) if it works for you.

**Comment by avg-I** [comment]
I think that that would be a right thing to do given the history.
For a context: I want to use your package as a part of a larger code base and I want to understand the license.
Thank you!

**Comment by kuba--** [comment]
Done.
